This will compile 
libft, calling to make file in /libft
server, calling mnakefile in /server
client, calling to makefile in /client 
gfx, calling to makefile in /client

once all or one binary is compiled they are renamed
and move to parent directory
